{"name": "Error when receiving an order by an unauthorized user", "status": "passed", "start": 1713109051707, "stop": 1713109052202, "uuid": "c0130451-a667-4e2b-a35d-dd0df41e5f08", "historyId": "f30074f872eb1ff256ae0c425638c0ad", "testCaseId": "f30074f872eb1ff256ae0c425638c0ad", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_user_without_authorization_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "System-Product"}, {"name": "thread", "value": "31366-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}