{"name": "Error during authorization with incorrect login and password", "status": "passed", "start": 1713109053951, "stop": 1713109054444, "uuid": "c98dd717-46e5-4d5b-86e5-18736ee68981", "historyId": "7ac1311b194a9e37c2cf50f2e37e5e29", "testCaseId": "7ac1311b194a9e37c2cf50f2e37e5e29", "fullName": "tests.test_login_user.TestLoginUser#test_user_login_incorrect_login_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "System-Product"}, {"name": "thread", "value": "31366-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}